### ISSUE TITLE
IPAddress.to Sphinx documentation doesn't link to anything

### ISSUE THREAD

**Issue by yoshizzle** [linode/linode_api4-python#119]
https://github.com/linode/python-linode-api/blob/dbcb8044099ae3ea1a6cdfebba6cfdadb428c6a6/linode/linode_client.py#L558

**Comment by Dorthu** [comment]
This doesn't link to anything because I haven't gotten to finishing up these docs - nothing in linode.objects has a page in sphinx yet.  Once the CLI is done and shipped I should have time to finish it up [and remove the warning that the docs are incomplete](http://python-linode-api.readthedocs.io/en/latest/)

**Comment by lgarber-akamai** [comment]
Closing because this issue appears to be resolved. Feel free to @ me if it is still relevant.
