### ISSUE TITLE
Ansible Linode Modules: Getting changes upstream

### ISSUE THREAD

**Issue by lwm** [linode/linode_api4-python#135]
Hi folks. I'm leading a bit on from https://github.com/linode/linode-cli/issues/46 but I'll get down to more brass tacks here. 

Basically, I'm trying to write Ansible modules for Linode automation, I've been accepted as module maintainer over in Ansible land but the existing module is using the deprecated API. There was some work around a new V4 module over at https://github.com/ansible/ansible/pull/41875 but as listed in https://github.com/ansible/ansible/pull/41875#issuecomment-419753721, I'd actually like for that module to just be a thin wrapper for **this** library.

I just wanted to check in and say hello and ask if you're actively accepting community contributions to this library and if you think my plan above is viable given the beta status of this library.

Looking forward to catching up Ansible with the new API! Thanks for your work.

**Comment by Dorthu** [comment]
First of all, thank you!  That's awesome, and we really appreciate it!

This library is definitely what you want, and I'll try my best to stay on top of pull requests and issues - if there's a feature you need that you feel is bigger than you want to take on, please open and issue and I'd be happy to knock it out.  I'm not an expert in ansible, but I've had a lot of success writing thin wrappers around this library in the past, and I'd be happy to support your effort however I can.

This library is still listed as "in beta" because I haven't found time to finish it's documentation yet, but the code is more or less settled (with a possible omission here or there).

**Comment by lwm** [comment]
Perfect! You will be hearing from me very soon :tada:

**Comment by lwm** [comment]
Here it commeesssss - https://github.com/ansible/ansible/pull/45902
