### ISSUE TITLE
inconsistent update behavior

### ISSUE THREAD

**Issue by muradm** [linode/linode_api4-python#184]
This works:
```
client = ...
instance = client.load(Instance, 123)
instance.tags = ['new-tags']
instance.save()
```
This does nothing:
```
client = ...
instance = Instance(client, 123) # from documentation it is not clear that this will make call at all
instance.tags = ['new-tags']
instance.save()
```
However this does work:
```
client = ...
volume = Volume(client, 1234)
volume.resize(25)
```
Same behavior for all objects. Is it intended?

Also could you confirm that first snippet will cause 2 remote API calls while second will cause 3 and how many call at what method calls will cause third snippet?

**Comment by lgarber-akamai** [comment]
> ... Is it intended?

This functionality is intended, although a bit confusing. This is because the `.save()` function relies on a populated resource to generate the PUT request body (see: https://github.com/linode/linode_api4-python/blob/dev/linode_api4/objects/base.py#L207).

In contrast, the `.resize(...)` function does not rely on any local values and only requires the new size argument and the ID of the volume.

> Also could you confirm that first snippet will cause 2 remote API calls while second will cause 3 and how many call at what method calls will cause third snippet?

Excluding client initialization requests, the following API requests should be made:

**First Snippet:**
- GET /linode/instances/123
- PUT /linode/instances/123

**Second Snippet:**
- PUT /linode/instances/123

The second snippet only makes one API request since the constructor for classes derived from `Base` does not automatically populate the object with data from the API.

We can definitely improve the documentation and potentially improve the constructor for resource classes, which would provide a much more intuitive user experience. I'll let you know when we have any updates about this 🙂
